<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_value</name>
   <tag></tag>
   <elementGuidId>3c4df0e4-9ba8-4ead-aed1-9cb20bb6a753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[2]/div/div/div[1]/form/div[1]/div/div[3]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div/div[1]/div[2]/div[2]/div/div/div[1]/form/div[1]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>8224c84f-8d77-4b07-a219-235e95d1b523</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
