<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submited_staus_value</name>
   <tag></tag>
   <elementGuidId>18c8fb6d-b59f-4828-839a-1e5e23faa658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[2]/div/div/div[1]/form/div[1]/div/div[3]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div/div[1]/div[2]/div[2]/div/div/div[1]/form/div[1]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>767ba188-7846-4aed-9edd-f41c34e05cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
