<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OrangeHRM_TestSuite_Claim</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>133f2c92-4593-4845-90d9-805fce8de31d</testSuiteGuid>
   <testCaseLink>
      <guid>d7d4657c-f58f-4244-a256-a3519acd3093</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven/TC_OrangeHRM_Claim_007</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c2878c8a-513a-4afa-952c-7ed564e7e955</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/OrangeHRM_Claim_TestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c2878c8a-513a-4afa-952c-7ed564e7e955</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>event</value>
         <variableId>ea551260-fe7e-4633-8264-546d05ab1858</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2878c8a-513a-4afa-952c-7ed564e7e955</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>currency</value>
         <variableId>ed6863a0-7a84-4dfa-86cf-ec27f988649f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddb02a96-cfdd-4c27-b93a-c78f2c4d5712</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
